# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: 'vs2017-win2016'

variables:
  - group: AzureSetup

steps:
- task: AzurePowerShell@4
  displayName: Create Resource Group -- $(RGN)
  inputs:
     azureSubscription: 'azureportal'
     ScriptType: InlineScript
     Inline: 'New-AzResourceGroup -Name $(RGN) -Location "$(ASPLocation)"' 
     azurePowerShellVersion: LatestVersion
- task: AzurePowerShell@4
  displayName: Craete App Service Plan --$(ASPName)
  inputs:
     azureSubscription: 'azureportal'
     ScriptType: InlineScript
     Inline: 'New-AzAppServicePlan -Name $(ASPName) -Location "$(ASPLocation)" -ResourceGroupName $(RGN) -Tier $(Tier)'
     azurePowerShellVersion: LatestVersion
- task : AzurePowerShell@4
  displayName: Create App Service for Hosting Dev Enironment
  inputs:
   azureSubscription: 'azureportal'
   ScriptType: InlineScript
   Inline: 'New-AzWebApp -ResourceGroupName $(RGN) -Name "$(Webappname-dev)" -Location "$(ASPLocation)" -AppServicePlan "$(ASPName)"'
   azurePowerShellVersion: LatestVersion


- task : AzurePowerShell@4
  displayName: Create App Service for Hosting Test Enironment
  inputs:
   azureSubscription: 'azureportal'
   ScriptType: InlineScript
   Inline: 'New-AzWebApp -ResourceGroupName $(RGN) -Name "$(Webappname-test)" -Location "$(ASPLocation)" -AppServicePlan "$(ASPName)"'
   azurePowerShellVersion: LatestVersion
   
 
    
  
   
