# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master


pool:
  vmImage: 'vs2017-win2016'

variables:
  - group: AzureSetup

steps:
- task: AzurePowerShell@4
  displayName: Get/ list Az Resource
  inputs:
     azureSubscription: 'azureportal'
     ScriptType: InlineScript
     Inline: 'New-AzAppServicePlan -Name $(ASPName) -Location $ASPLocation -ResourceGroupName $RGN -Tier $Tier'
     azurePowerShellVersion: LatestVersion
    
  
   
